/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 72e87ea6780dcfa32a69e085f3a02d21)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SyncedStateServer" | "SessionDurableObject";
	}
	interface Env {
		LISTING_IMAGES: R2Bucket;
		campusmarket_db: D1Database;
		ASSETS: Fetcher;
		APP_URL: "https://campus-market.hamzaalkasasbeh96.workers.dev";
		SYNCED_STATE_SERVER: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
		SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_URL">> {}
}
